version: '3.8'

networks:
  tumivlan:

services:
  laravel:
    image: webdevops/php-nginx:8.1
    container_name: laravel
    working_dir: /app
    restart: on-failure
    ports:
      - "84:80"
    volumes:
      - ./:/app:delegated
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    networks:
      - tumivlan

  mysql:
    image: mysql:8.0.36
    container_name: mysql
    working_dir: /app
    restart: on-failure
    networks:
      - tumivlan
    logging:
      driver: local
      options:
        max-size: 100m
    security_opt:
      - no-new-privileges:true
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: awdFTHjil
      MYSQL_DATABASE: laravel
