<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Employee extends Model
{
    protected $fillable = [
        'user_id',
        'department_id',
        'name',
        'lastname',
        'document',
        'type_document',
    ];

    public function department()
    {
        return $this->belongsTo('App\Models\Department');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function purchaseorders()
    {
        return $this->hasMany('App\Models\PurchaseOrder');
    }

    public function saleorders()
    {
        return $this->hasMany('App\Models\SaleOrder');
    }
}
