<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Provider extends Model
{

    protected $fillable = [
        'name',
        'address',
        'phone',
    ];

    public function enterprises()
    {
        return $this->belongsToMany('App\Models\Enterprise');
    }

    public function purchaseorders()
    {
        return $this->hasMany('App\Models\PurchaseOrder');
    }
}
