<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class SaleOrder extends Model
{
    protected $fillable = [
        'serie',
        'correlative',
        'stored_at',
        'state',
    ];

    public function employee()
    {
        return $this->belongsTo('App\Models\Employee');
    }
}
