<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class User extends Model
{
    protected $fillable = [
        'username',
        'password',
        'role',
    ];

    public function employee()
    {
        return $this->hasOne(\App\Models\Employee);
    }
}
